### ISSUE TITLE
[Ionic] Versión 3 sdk con actualización de ubicación usuario

### ISSUE THREAD

**Issue by luch1u** [lazarilloapp/demoIonicPlugin#2]
- [ ] Agregar permisos a repo de ejemplo
- [ ] Actualizar ubicación
- [ ] Probar como funciona con beacons

**Comment by renatojobal** [comment]
Estos issues se trabajaran en el repo de [lazarillo sdk](https://github.com/lazarilloapp/lz-sdk-plugin)
